name: RotsteinManagement
version: '${project.version}'
main: de.janoschbl.teamsmp.Main
api-version: '1.21'
commands:
  team:
    description: Team management commands
  teamchat:
    description: Team Chat Command
    aliases:
      - tc
      - teamc
      - tchat
      - teammsg
  admin:
    description: Admin Command
permissions:
  team.delete:
    description: Allows the staff team to delete a team
    default: op
  team.create:
    description: Allows the staff team to create a team
    default: op
  team.add:
    description: Allows the staff team to add players to a team
    default: op
  team.remove:
    description: Allows the staff team to remove players from a team
    default: op
  team.chat:
    description: Allows the user to use team chat
    default: true
